import type { Metadata } from 'next'
import { Geist, Geist_Mono, Outfit, Public_Sans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import ScrollToTop from '@/components/layout/ScrollToTop'

const publicSansHeading = Public_Sans({
  subsets: ['latin'],
  variable: '--font-heading',
})

const outfit = Outfit({ subsets: ['latin'], variable: '--font-sans' })

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: LayoutProps<'/'>) => {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        'font-sans',
        outfit.variable,
        publicSansHeading.variable
      )}
    >
      <body className="min-h-screen">
        <ScrollToTop />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
